# Site settings
title: Turingki's Lab
email: turingki@yeah.net
description: > # this means to ignore newlines until "baseurl:"
 This site is uesd to test some interesting stuffs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://turingki.com" # the base hostname & protocol for your site
github_username:  TuringKi

# Build settings
markdown: kramdown
